apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations: 
    # create ingress controller based on nginx project
    kubernetes.io/ingress.class: nginx
    # remove the "/api part"
    nginx.ingress.kubernetes.io/rewrite-target: /    
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: client-cluster-ip-service
              servicePort: 3000
          # redirect "/api/" to the server
          - path: /api/
            backend:
              serviceName: server-cluster-ip-service
              servicePort: 5000