# object telling cert manager where it should go to get a certificate
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 'tkousek2002@yahoo.com'
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}